# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_module_text": "00_core.ipynb",
         "write_module_text": "00_core.ipynb",
         "clear_all_modules": "00_core.ipynb",
         "simple_export_one_nb": "00_core.ipynb",
         "simple_export_all_nb": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Isaac-Flath.github.io/nbdev_minimum/"

git_url = "https://github.com/Isaac-Flath/nbdev_minimum/tree/{branch}/"

def custom_doc_links(name): return None
